const states = [
  {
    name: 'Alabama',
    hebName: 'אלבמה',
    symbol: 'AL',
  },
  {
    name: 'Alaska',
    hebName: 'אלסקה',
    symbol: 'AK',
  },
  {
    name: 'Arizona',
    hebName: 'אריזונה',
    symbol: 'AZ',
  },
  {
    name: 'Arkansas',
    hebName: 'ארקנסו',
    symbol: 'AR',
  },
  {
    name: 'California',
    hebName: 'קליפורניה',
    symbol: 'CA',
  },
  {
    name: 'Colorado',
    hebName: 'קולורדו',
    symbol: 'CO',
  },
  {
    name: 'Connecticut',
    hebName: 'קונטיקט',
    symbol: 'CT',
  },
  {
    name: 'Delaware',
    hebName: 'דלאוור',
    symbol: 'DE',
  },
  {
    name: 'Florida',
    hebName: 'פלורידה',
    symbol: 'FL',
  },
  {
    name: 'Georgia',
    hebName: 'ג\'ורג\'יה',
    symbol: 'GA',
  },
  {
    name: 'Hawaii',
    hebName: 'הוואי',
    symbol: 'HI',
  },
  {
    name: 'Idaho',
    hebName: 'אידהו',
    symbol: 'ID',
  },
  {
    name: 'Illinois',
    hebName: 'אילינוי',
    symbol: 'IL',
  },
  {
    name: 'Indiana',
    hebName: 'אינדיאנה',
    symbol: 'IN',
  },
  {
    name: 'Iowa',
    hebName: 'איווה',
    symbol: 'IA',
  },
  {
    name: 'Kansas',
    hebName: 'קנזאס',
    symbol: 'KS',
  },
  {
    name: 'Kentucky',
    hebName: 'קנטאקי',
    symbol: 'KY',
  },
  {
    name: 'Louisiana',
    hebName: 'לואיזיאנה',
    symbol: 'LA',
  },
  {
    name: 'Maine',
    hebName: 'מיין',
    symbol: 'ME',
  },
  {
    name: 'Maryland',
    hebName: 'מרילנד',
    symbol: 'MD',
  },
  {
    name: 'Massachusetts',
    hebName: 'מסצ\'וסטס',
    symbol: 'MA',
  },
  {
    name: 'Michigan',
    hebName: 'מישיגן',
    symbol: 'MI',
  },
  {
    name: 'Minnesota',
    hebName: 'מיניסוטה',
    symbol: 'MN',
  },
  {
    name: 'Mississippi',
    hebName: 'מיסיסיפי',
    symbol: 'MS',
  },
  {
    name: 'Missouri',
    hebName: 'מיזורי',
    symbol: 'MO',
  },
  {
    name: 'Montana',
    hebName: 'מונטנה',
    symbol: 'MT',
  },
  {
    name: 'Nebraska',
    hebName: 'נברסקה',
    symbol: 'NE',
  },
  {
    name: 'Nevada',
    hebName: 'נוואדה',
    symbol: 'NV',
  },
  {
    name: 'New Hampshire',
    hebName: 'ניו המפשייר',
    symbol: 'NH',
  },
  {
    name: 'New Jersey',
    hebName: 'ניו ג\'רזי',
    symbol: 'NJ',
  },
  {
    name: 'New Mexico',
    hebName: 'ניו מקסיקו',
    symbol: 'NM',
  },
  {
    name: 'New York',
    hebName: 'ניו יורק',
    symbol: 'NY',
  },
  {
    name: 'North Carolina',
    hebName: 'צפון קרולינה',
    symbol: 'NC',
  },
  {
    name: 'North Dakota',
    hebName: 'צפון דקוטה',
    symbol: 'ND',
  },
  {
    name: 'Ohio',
    hebName: 'אוהיו',
    symbol: 'OH',
  },
  {
    name: 'Oklahoma',
    hebName: 'אוקלהומה',
    symbol: 'OK',
  },
  {
    name: 'Oregon',
    hebName: 'אורגון',
    symbol: 'OR',
  },
  {
    name: 'Pennsylvania',
    hebName: 'פנסילבניה',
    symbol: 'PA',
  },
  {
    name: 'Rhode Island',
    hebName: 'רוד איילנד',
    symbol: 'RI',
  },
  {
    name: 'South Carolina',
    hebName: 'דרום קרולינה',
    symbol: 'SC',
  },
  {
    name: 'South Dakota',
    hebName: 'דרום דקוטה',
    symbol: 'SD',
  },
  {
    name: 'Tennessee',
    hebName: 'טנסי',
    symbol: 'TN',
  },
  {
    name: 'Texas',
    hebName: 'טקסס',
    symbol: 'TX',
  },
  {
    name: 'Utah',
    hebName: 'יוטה',
    symbol: 'UT',
  },
  {
    name: 'Vermont',
    hebName: 'ורמונט',
    symbol: 'VT',
  },
  {
    name: 'Virginia',
    hebName: 'וירג\'יניה',
    symbol: 'VA',
  },
  {
    name: 'Washington',
    hebName: 'וושינגטון',
    symbol: 'WA',
  },
  {
    name: 'West Virginia',
    hebName: 'מערב וירג\'יניה',
    symbol: 'WV',
  },
  {
    name: 'Wisconsin',
    hebName: 'ויסקונסין',
    symbol: 'WI',
  },
  {
    name: 'Wyoming',
    hebName: 'ויומינג',
    symbol: 'WY',
  },
]

const senate = [
  {
    name: 'Helen Burgess',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NY',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Julia Conrad',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NY',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Lynne Watson',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NC',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Ward Ewing',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NC',
  },
  {
    name: 'Terry Bruce',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MS',
  },
  {
    name: 'Jayne Lucas',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MS',
  },
  {
    name: 'Helga Beard',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'TX',
  },
  {
    name: 'Hale Johnston',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'TX',
  },
  {
    name: 'Colette Robbins',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'KY',
  },
  {
    name: 'Harris Hughes',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'IN',
  },
  {
    name: 'Jacquelyn Collier',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'FL',
  },
  {
    name: 'Kathryn Bernard',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'KS',
  },
  {
    name: 'Annette Johnson',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MS',
  },
  {
    name: 'Shanna Alston',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'LA',
  },
  {
    name: 'Hollie Bell',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'CO',
  },
  {
    name: 'Petty Gilbert',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'ID',
  },
  {
    name: 'Hattie Fleming',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'WY',
  },
  {
    name: 'Morton Barnes',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'IA',
  },
  {
    name: 'Camille Montgomery',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'DE',
  },
  {
    name: 'Sylvia Kim',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'ME',
  },
  {
    name: 'Herrera Ellison',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MI',
  },
  {
    name: 'Warner Alvarado',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MN',
  },
  {
    name: 'Poole Horne',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NE',
  },
  {
    name: 'Clarke Cameron',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NJ',
  },
  {
    name: 'Tameka Fox',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NH',
  },
  {
    name: 'Candace Fisher',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'SD',
  },
  {
    name: 'Gamble Mccullough',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'UT',
  },
  {
    name: 'Maynard Padilla',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'RI',
  },
  {
    name: 'Tami Alford',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MA',
  },
  {
    name: 'Abbott Juarez',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MD',
  },
  {
    name: 'Smith English',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'CT',
  },
  {
    name: 'Quinn Hood',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'HI',
  },
  {
    name: 'Claudette Ryan',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'GA',
  },
  {
    name: 'English Pate',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'IL',
  },
  {
    name: 'Berg Vincent',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NM',
  },
  {
    name: 'Stuart Espinoza',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NV',
  },
  {
    name: 'Cox Mayer',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'OK',
  },
  {
    name: 'Cline Powers',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ND',
  },
  {
    name: 'Erika Stanton',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MT',
  },
  {
    name: 'Katharine Sykes',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AL',
  },
  {
    name: 'Lidia Le',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'OH',
  },
  {
    name: 'Alissa Cortez',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MO',
  },
  {
    name: 'Mona Gentry',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'PA',
  },
  {
    name: 'Mercer Flynn',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'OR',
  },
  {
    name: 'Lawanda Norris',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'SC',
  },
  {
    name: 'Wilkerson May',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'RI',
  },
  {
    name: 'Craft Peterson',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'VT',
  },
  {
    name: 'Willa Williams',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'WA',
  },
  {
    name: 'Hope Francis',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'AZ',
  },
  {
    name: 'Jenifer Bray',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'AR',
  },
  {
    name: 'Manning Mckenzie',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'WV',
  },
  {
    name: 'Whitney Long',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'ME',
  },
  {
    name: 'Gould Hicks',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'WI',
  },
  {
    name: 'Nolan Cervantes',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'PA',
  },
  {
    name: 'Autumn Sears',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MD',
  },
  {
    name: 'Clements Dunn',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'AR',
  },
  {
    name: 'Walter Forbes',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'AK',
  },
  {
    name: 'Clare Wall',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'ME',
  },
  {
    name: 'Rivera Silva',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'IN',
  },
  {
    name: 'Kerr Finch',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'HI',
  },
  {
    name: 'Ava Sloan',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'ND',
  },
  {
    name: 'Rosalinda Mccarty',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MN',
  },
  {
    name: 'Dillon Hooper',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'DE',
  },
  {
    name: 'Hughes Eaton',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'KS',
  },
  {
    name: 'Mcneil Merritt',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'KY',
  },
  {
    name: 'Deidre Whitney',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NH',
  },
  {
    name: 'Mamie Foreman',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'OK',
  },
  {
    name: 'Cotton Hensley',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'IA',
  },
  {
    name: 'Annabelle Compton',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'FL',
  },
  {
    name: 'Cummings Ball',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MI',
  },
  {
    name: 'Ronda Fitzgerald',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'IL',
  },
  {
    name: 'Darla Boone',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ID',
  },
  {
    name: 'Padilla Wilkinson',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MA',
  },
  {
    name: 'Sweeney Cabrera',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NJ',
  },
  {
    name: 'Raquel Dawson',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'OH',
  },
  {
    name: 'Glenn Fischer',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'LA',
  },
  {
    name: 'Walton Marsh',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MT',
  },
  {
    name: 'Denise Arnold',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AL',
  },
  {
    name: 'Steele Horn',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'OR',
  },
  {
    name: 'Nicole Blanchard',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'SC',
  },
  {
    name: 'Estelle Mcpherson',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NV',
  },
  {
    name: 'Natasha Booker',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'GA',
  },
  {
    name: 'Mcgowan Ayers',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'VA',
  },
  {
    name: 'Minerva Burke',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'WA',
  },
  {
    name: 'Anastasia Mendoza',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WY',
  },
  {
    name: 'Whitaker Oconnor',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'CA',
  },
  {
    name: 'Bright George',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'CT',
  },
  {
    name: 'Kasey Moran',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'AZ',
  },
  {
    name: 'Jessica Serrano',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'VT',
  },
  {
    name: 'Hayes Poole',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'TN',
  },
  {
    name: 'Byers Colon',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'UT',
  },
  {
    name: 'Hazel Mason',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'CO',
  },
  {
    name: 'Kristie Wiggins',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'AK',
  },
  {
    name: 'Elvia Garcia',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'AR',
  },
  {
    name: 'Kristin Mathis',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'CA',
  },
  {
    name: 'Nona Strong',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WI',
  },
  {
    name: 'Henderson Carroll',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NM',
  },
  {
    name: 'Sharp Baker',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NE',
  },
  {
    name: 'Stephens Sampson',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'SD',
  },
  {
    name: 'Antonia Goff',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'TN',
  },
]

const house = [
  {
    name: 'Ann Brennan',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NY',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Harvey King',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NY',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Flora Anthony',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NC',
  },
  {
    name: 'Kara Phelps',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NC',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Jessica Riggs',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MS',
  },
  {
    name: 'Mariana Sosa',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MS',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Swanson Blake',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'TX',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Sonya Washington',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'TX',
  },
  {
    name: 'Eula Frye',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'KY',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Leblanc Marquez',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'IN',
  },
  {
    name: 'Nettie Odom',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'FL',
  },
  {
    name: 'Lucia Jacobs',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'KS',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Acevedo Dean',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MS',
  },
  {
    name: 'Meagan Burch',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'LA',
  },
  {
    name: 'Hunter Garrett',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'CO',
  },
  {
    name: 'Sheila Gillespie',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'ID',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Jackson Solis',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WY',
  },
  {
    name: 'Cassie Lyons',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'IA',
  },
  {
    name: 'Jackie Cain',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'DE',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Butler Berry',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ME',
  },
  {
    name: 'Janelle Alston',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MI',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Leola Hatfield',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MN',
  },
  {
    name: 'Glenda Norman',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NE',
  },
  {
    name: 'Yang Bender',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NJ',
  },
  {
    name: 'Barlow Berg',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NH',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Janna Riley',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'SD',
  },
  {
    name: 'Velazquez Dale',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'UT',
  },
  {
    name: 'Frieda Roach',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'RI',
  },
  {
    name: 'Hardin Hutchinson',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MA',
  },
  {
    name: 'Judy Mcclure',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MD',
  },
  {
    name: 'Barbra Irwin',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'CT',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Bird Terry',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'HI',
  },
  {
    name: 'Kristine Pearson',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'GA',
  },
  {
    name: 'Fernandez Buchanan',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'IL',
  },
  {
    name: 'Geneva Nash',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NM',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Calderon William',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NV',
  },
  {
    name: 'Patti Cruz',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'OK',
  },
  {
    name: 'Ada Torres',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'ND',
  },
  {
    name: 'Burgess Mccarthy',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MT',
  },
  {
    name: 'Miranda Hayes',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'AL',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Hart Reeves',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'OH',
  },
  {
    name: 'Ellen Ortiz',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MO',
  },
  {
    name: 'Shaffer Dickson',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'PA',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Ana Snyder',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'OR',
  },
  {
    name: 'Alissa Klein',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'SC',
  },
  {
    name: 'Suzette Ewing',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'RI',
  },
  {
    name: 'Callie Mack',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'VT',
  },
  {
    name: 'Joyce Wilder',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'WA',
  },
  {
    name: 'Angelia Curtis',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'AZ',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Young Craig',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'AR',
  },
  {
    name: 'Underwood Pruitt',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'WV',
  },
  {
    name: 'Alba Keller',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'ME',
  },
  {
    name: 'England Molina',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'WI',
  },
  {
    name: 'Shari Dominguez',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'PA',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Terrell Perez',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MD',
  },
  {
    name: 'Kathrine Watts',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'AR',
  },
  {
    name: 'Thelma Wilkinson',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'AK',
  },
  {
    name: 'Mcintyre Baker',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'ME',
  },
  {
    name: 'Cindy Crosby',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'IN',
  },
  {
    name: 'Jodi Armstrong',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'HI',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Alejandra Christensen',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ND',
  },
  {
    name: 'Allison Frank',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MN',
  },
  {
    name: 'May Dunn',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'DE',
  },
  {
    name: 'Morrison Terrell',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'KS',
  },
  {
    name: 'Waters Tanner',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'KY',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Rosie Hull',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NH',
  },
  {
    name: 'Anthony Gilliam',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'OK',
  },
  {
    name: 'Vance Patrick',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'IA',
  },
  {
    name: 'Alison Gibson',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'FL',
  },
  {
    name: 'Lottie Tillman',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MI',
  },
  {
    name: 'York Humphrey',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'IL',
  },
  {
    name: 'Carpenter Carrillo',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'ID',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Melton Small',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MA',
  },
  {
    name: 'Rocha Weber',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NJ',
  },
  {
    name: 'Leah Reynolds',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'OH',
  },
  {
    name: 'Sloan Vaughan',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'LA',
  },
  {
    name: 'Crosby Manning',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MT',
  },
  {
    name: 'Lucinda Pratt',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'AL',
  },
  {
    name: 'Pat Mcguire',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'OR',
  },
  {
    name: 'Nell Schmidt',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'SC',
  },
  {
    name: 'Isabelle Griffith',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NV',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Adkins Miles',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'GA',
  },
  {
    name: 'Dawn Saunders',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'VA',
  },
  {
    name: 'Stafford Wallace',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'WA',
  },
  {
    name: 'Marietta Weiss',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'WY',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Glass Schneider',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'CA',
  },
  {
    name: 'Latasha Schultz',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'CT',
  },
  {
    name: 'Margaret Parrish',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'AZ',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Latoya Hendrix',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'VT',
  },
  {
    name: 'Blanchard Newman',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'TN',
  },
  {
    name: 'Elva Allison',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'UT',
  },
  {
    name: 'Fields Wooten',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'CO',
  },
  {
    name: 'Barbara Cameron',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AK',
  },
  {
    name: 'Blair Lee',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'AR',
  },
  {
    name: 'Hester Conway',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'CA',
  },
  {
    name: 'Lenore Jacobson',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'WI',
  },
  {
    name: 'Penny Davenport',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NM',
  },
  {
    name: 'Robert Noel',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NE',
  },
  {
    name: 'Nicholson Rogers',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'SD',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Downs Perkins',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'TN',
  },
  {
    name: 'Ginger Bolton',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NY',
  },
  {
    name: 'Holden Shaffer',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NY',
  },
  {
    name: 'Brooke Swanson',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NC',
  },
  {
    name: 'Lelia Wagner',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NC',
  },
  {
    name: 'Kirkland Cummings',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MS',
  },
  {
    name: 'Magdalena Christensen',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MS',
  },
  {
    name: 'Joanne Richardson',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'TX',
  },
  {
    name: 'Jackie White',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'TX',
  },
  {
    name: 'Lara Buchanan',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'KY',
  },
  {
    name: 'Duran Ballard',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'IN',
  },
  {
    name: 'Justice Ingram',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'FL',
  },
  {
    name: 'Rosie Rodriquez',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'KS',
  },
  {
    name: 'Stefanie Lynch',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MS',
  },
  {
    name: 'Carmen Haynes',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'LA',
  },
  {
    name: 'Winifred Sweet',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'CO',
  },
  {
    name: 'Mandy Holder',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'ID',
  },
  {
    name: 'Barron Workman',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'WY',
  },
  {
    name: 'Kelley Rivers',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'IA',
  },
  {
    name: 'Mclean Dixon',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'DE',
  },
  {
    name: 'Violet Conner',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'ME',
  },
  {
    name: 'Cole Mcgowan',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MI',
  },
  {
    name: 'Elnora Yates',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MN',
  },
  {
    name: 'Castaneda Golden',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NE',
  },
  {
    name: 'Garcia Odom',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NJ',
  },
  {
    name: 'Jami Lloyd',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NH',
  },
  {
    name: 'Merle Foreman',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'SD',
  },
  {
    name: 'Winters Turner',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'UT',
  },
  {
    name: 'Ann Spencer',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'RI',
  },
  {
    name: 'Latonya Fields',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MA',
  },
  {
    name: 'Lowe Bowen',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MD',
  },
  {
    name: 'Miller Stuart',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'CT',
  },
  {
    name: 'Sheppard Avery',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'HI',
  },
  {
    name: 'Malone Villarreal',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'GA',
  },
  {
    name: 'Blanca Pacheco',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'IL',
  },
  {
    name: 'Serrano Blankenship',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NM',
  },
  {
    name: 'Obrien Mccarthy',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NV',
  },
  {
    name: 'Alexander Myers',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'OK',
  },
  {
    name: 'Estrada Albert',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'ND',
  },
  {
    name: 'Genevieve Hull',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MT',
  },
  {
    name: 'Stuart Collier',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'AL',
  },
  {
    name: 'Katharine Bullock',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'OH',
  },
  {
    name: 'Gill Giles',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MO',
  },
  {
    name: 'Drake Hayes',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'PA',
  },
  {
    name: 'Taylor Richmond',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'OR',
  },
  {
    name: 'Barrett Joseph',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'SC',
  },
  {
    name: 'Strickland Barrera',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'RI',
  },
  {
    name: 'Alice Pitts',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'VT',
  },
  {
    name: 'Aimee Powell',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'WA',
  },
  {
    name: 'Antoinette Conway',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'AZ',
  },
  {
    name: 'Kane Hutchinson',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'AR',
  },
  {
    name: 'Shannon Gordon',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WV',
  },
  {
    name: 'Queen Nash',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ME',
  },
  {
    name: 'Bell Owens',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WI',
  },
  {
    name: 'Susanna Gutierrez',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'PA',
  },
  {
    name: 'Perez Gonzalez',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MD',
  },
  {
    name: 'Guy Kane',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'AR',
  },
  {
    name: 'Maryellen Huff',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'AK',
  },
  {
    name: 'Howard Serrano',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'ME',
  },
  {
    name: 'Stevenson Leblanc',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'IN',
  },
  {
    name: 'Monique Chase',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'HI',
  },
  {
    name: 'Lina Moore',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ND',
  },
  {
    name: 'Elba Hunt',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MN',
  },
  {
    name: 'Vega Foley',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'DE',
  },
  {
    name: 'Clara Russo',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'KS',
  },
  {
    name: 'Roxie Robles',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'KY',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Pate Roth',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NH',
  },
  {
    name: 'Kris Woodard',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'OK',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Candy Head',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'IA',
  },
  {
    name: 'Cervantes Faulkner',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'FL',
  },
  {
    name: 'Frederick Allen',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MI',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Woodward Walsh',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'IL',
  },
  {
    name: 'Minerva Britt',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'ID',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Ila Forbes',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MA',
  },
  {
    name: 'Luna Morrow',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NJ',
  },
  {
    name: 'Eileen Holcomb',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'OH',
  },
  {
    name: 'Jerri Rhodes',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'LA',
  },
  {
    name: 'Atkins Martinez',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MT',
  },
  {
    name: 'Delacruz Wiggins',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AL',
  },
  {
    name: 'Joyce Bradley',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'OR',
  },
  {
    name: 'Victoria Fitzpatrick',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'SC',
  },
  {
    name: 'Clarissa Jennings',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NV',
  },
  {
    name: 'Gladys Vargas',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'GA',
  },
  {
    name: 'Roberta Waters',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'VA',
  },
  {
    name: 'Alisha Townsend',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'WA',
  },
  {
    name: 'Burns Levy',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WY',
  },
  {
    name: 'Burks Clay',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'CA',
  },
  {
    name: 'Carole Cline',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'CT',
  },
  {
    name: 'June Thornton',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'AZ',
  },
  {
    name: 'Beatrice Wood',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'VT',
  },
  {
    name: 'Marion Salas',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'TN',
  },
  {
    name: 'Sherri Berger',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'UT',
  },
  {
    name: 'Jill Riley',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'CO',
  },
  {
    name: 'Ebony Dawson',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'AK',
  },
  {
    name: 'Lana Dickerson',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AR',
  },
  {
    name: 'Eula Lawson',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'CA',
  },
  {
    name: 'Mccoy Larsen',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'WI',
  },
  {
    name: 'Nanette Macias',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NM',
  },
  {
    name: 'Conner Mayo',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NE',
  },
  {
    name: 'Reeves Puckett',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'SD',
  },
  {
    name: 'Pat Frazier',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'TN',
  },
  {
    name: 'Rebecca Cardenas',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NY',
  },
  {
    name: 'Palmer Joyce',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NY',
  },
  {
    name: 'Darcy Erickson',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NC',
  },
  {
    name: 'Mejia Hurley',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NC',
  },
  {
    name: 'Sandra Chase',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MS',
  },
  {
    name: 'Oliver Dominguez',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MS',
  },
  {
    name: 'Lynn Acosta',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'TX',
  },
  {
    name: 'Katherine Trujillo',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'TX',
  },
  {
    name: 'Rowe Gross',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'KY',
  },
  {
    name: 'Olsen Daugherty',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'IN',
  },
  {
    name: 'Garner Francis',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'FL',
  },
  {
    name: 'Cherry Farmer',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'KS',
  },
  {
    name: 'Fields Gates',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MS',
  },
  {
    name: 'Anita Paul',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'LA',
  },
  {
    name: 'Kristina Holcomb',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'CO',
  },
  {
    name: 'Lara Clay',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'ID',
  },
  {
    name: 'Leblanc Schmidt',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WY',
  },
  {
    name: 'Tami Sharpe',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'IA',
  },
  {
    name: 'Melissa Adams',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'DE',
  },
  {
    name: 'Larsen Miranda',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ME',
  },
  {
    name: 'Pauline Cook',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MI',
  },
  {
    name: 'Howe Le',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MN',
  },
  {
    name: 'Haney Cooke',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NE',
  },
  {
    name: 'Lilian Wilder',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NJ',
  },
  {
    name: 'Vaughan Carter',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NH',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Mccormick Moody',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'SD',
  },
  {
    name: 'Lynda Bradford',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'UT',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Frank Hinton',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'RI',
  },
  {
    name: 'Mathis Payne',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MA',
  },
  {
    name: 'Burks Barron',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MD',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Morales French',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'CT',
  },
  {
    name: 'Aurelia Hendrix',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'HI',
  },
  {
    name: 'Monique Mclean',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'GA',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Lowery Guthrie',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'IL',
  },
  {
    name: 'Kendra Guy',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NM',
  },
  {
    name: 'Angelita Kirby',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NV',
  },
  {
    name: 'Daugherty Hall',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'OK',
  },
  {
    name: 'Hansen Hudson',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'ND',
  },
  {
    name: 'Sharon Huber',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MT',
  },
  {
    name: 'Amber Saunders',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AL',
  },
  {
    name: 'Petty Johnston',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'OH',
  },
  {
    name: 'Schneider Avila',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MO',
  },
  {
    name: 'Holland Garza',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'PA',
  },
  {
    name: 'Jean Green',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'OR',
  },
  {
    name: 'Mollie Huff',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'SC',
  },
  {
    name: 'Delia Fleming',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'RI',
  },
  {
    name: 'Lidia Wyatt',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'VT',
  },
  {
    name: 'Lacey Newton',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'WA',
  },
  {
    name: 'Sims Martinez',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'AZ',
  },
  {
    name: 'Julie Waller',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AR',
  },
  {
    name: 'Nettie Dunn',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'WV',
  },
  {
    name: 'Latisha Patterson',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ME',
  },
  {
    name: 'Lowe Rutledge',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'WI',
  },
  {
    name: 'Barlow Heath',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'PA',
  },
  {
    name: 'Ava Whitfield',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MD',
  },
  {
    name: 'Alta Bentley',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'AR',
  },
  {
    name: 'Dillard Myers',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AK',
  },
  {
    name: 'Serena Russo',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'ME',
  },
  {
    name: 'Kayla Harper',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'IN',
  },
  {
    name: 'Fulton Wooten',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'HI',
  },
  {
    name: 'Caroline Henson',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'ND',
  },
  {
    name: 'Pamela Cabrera',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MN',
  },
  {
    name: 'Trisha Campos',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'DE',
  },
  {
    name: 'Alma Lancaster',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'KS',
  },
  {
    name: 'Golden Arnold',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'KY',
  },
  {
    name: 'Bennett Case',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NH',
  },
  {
    name: 'Williamson Cole',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'OK',
  },
  {
    name: 'Carolyn Hickman',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'IA',
  },
  {
    name: 'Kent Tillman',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'FL',
  },
  {
    name: 'Rosie Burns',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MI',
  },
  {
    name: 'Michelle Chan',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'IL',
  },
  {
    name: 'Joseph Randall',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'ID',
  },
  {
    name: 'Keri Harrington',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MA',
  },
  {
    name: 'Pearson Higgins',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NJ',
  },
  {
    name: 'Soto Hester',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'OH',
    engNote: 'GraphQL subscriptions have to be defined in the schema, just like queries and mutations:',
    hebNote: 'תג קאנוניקל לכל עמוד באתר, הכתובת חייבת להיות מקורית (ללא פרמטרים) אבסולוטית ולא רלטיבית.'
  },
  {
    name: 'Nadine Kennedy',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'LA',
  },
  {
    name: 'Warner Martin',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MT',
  },
  {
    name: 'Bray Rasmussen',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'AL',
  },
  {
    name: 'Savage Juarez',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'OR',
  },
  {
    name: 'Sheree Byers',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'SC',
  },
  {
    name: 'Sandy Hernandez',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NV',
  },
  {
    name: 'Margo Howard',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'GA',
  },
  {
    name: 'Shelia Abbott',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'VA',
  },
  {
    name: 'Peterson Yates',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WA',
  },
  {
    name: 'Saundra Collins',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'WY',
  },
  {
    name: 'Dixon Williamson',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'CA',
  },
  {
    name: 'Yang Glenn',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'CT',
  },
  {
    name: 'Stephens Sparks',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'AZ',
  },
  {
    name: 'Velma Cervantes',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'VT',
  },
  {
    name: 'Kelley Larsen',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'TN',
  },
  {
    name: 'Tanya Clements',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'UT',
  },
  {
    name: 'Galloway Mcfadden',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'CO',
  },
  {
    name: 'Goff Lucas',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'AK',
  },
  {
    name: 'Patti Diaz',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'AR',
  },
  {
    name: 'Kasey Daniels',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'CA',
  },
  {
    name: 'Vicky Sanders',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WI',
  },
  {
    name: 'Barker Perez',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NM',
  },
  {
    name: 'Thompson Benson',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NE',
  },
  {
    name: 'Sosa Rojas',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'SD',
  },
  {
    name: 'Ashley Montoya',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'TN',
  },
  {
    name: 'Harris Whitney',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NY',
  },
  {
    name: 'Sandoval Burton',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NY',
  },
  {
    name: 'Day Reeves',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NC',
  },
  {
    name: 'James Garcia',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NC',
  },
  {
    name: 'Gayle Luna',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MS',
  },
  {
    name: 'Lambert Lancaster',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'MS',
  },
  {
    name: 'Angel Duran',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'TX',
  },
  {
    name: 'Aurora Pierce',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'TX',
  },
  {
    name: 'Daisy Klein',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'KY',
  },
  {
    name: 'Paulette Mcguire',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'IN',
  },
  {
    name: 'Rae Boyer',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'FL',
  },
  {
    name: 'Jasmine Lamb',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'KS',
  },
  {
    name: 'Patrica Winters',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MS',
  },
  {
    name: 'Cindy Hyde',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'LA',
  },
  {
    name: 'Blanchard Clark',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'CO',
  },
  {
    name: 'Martina Obrien',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'ID',
  },
  {
    name: 'Warner Fulton',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WY',
  },
  {
    name: 'Holder Mejia',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'IA',
  },
  {
    name: 'Carpenter Floyd',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'DE',
  },
  {
    name: 'Pansy Barnett',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'ME',
  },
  {
    name: 'Ingram Coffey',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MI',
  },
  {
    name: 'Hooper Day',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MN',
  },
  {
    name: 'Annette Booth',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NE',
  },
  {
    name: 'Camacho Ballard',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NJ',
  },
  {
    name: 'Greene Marsh',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NH',
  },
  {
    name: 'Huber Oliver',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'SD',
  },
  {
    name: 'Sheila Flynn',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'UT',
  },
  {
    name: 'Angeline Dejesus',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'RI',
  },
  {
    name: 'Salazar Sandoval',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MA',
  },
  {
    name: 'Sexton Potts',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MD',
  },
  {
    name: 'Suarez Stephenson',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'CT',
  },
  {
    name: 'Janell Watson',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'HI',
  },
  {
    name: 'Page Mckay',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'GA',
  },
  {
    name: 'Addie Vega',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'IL',
  },
  {
    name: 'Macdonald Guerrero',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NM',
  },
  {
    name: 'Deloris Wilson',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NV',
  },
  {
    name: 'Renee Sutton',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'OK',
  },
  {
    name: 'Emilia Gamble',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ND',
  },
  {
    name: 'Hancock Christian',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MT',
  },
  {
    name: 'Christina Daniel',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'AL',
  },
  {
    name: 'King Skinner',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'OH',
  },
  {
    name: 'Ida Dalton',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MO',
  },
  {
    name: 'Loretta Robertson',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'PA',
  },
  {
    name: 'Rhoda Mathews',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'OR',
  },
  {
    name: 'Adela Williams',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'SC',
  },
  {
    name: 'Shauna Estes',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'RI',
  },
  {
    name: 'Clarice Joyner',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'VT',
  },
  {
    name: 'Rene Maldonado',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'WA',
  },
  {
    name: 'Amie Alford',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AZ',
  },
  {
    name: 'Angelica Bowers',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AR',
  },
  {
    name: 'Erickson Leon',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'WV',
  },
  {
    name: 'Abbott Cook',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'ME',
  },
  {
    name: 'Barker Grimes',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'WI',
  },
  {
    name: 'Gross Atkins',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'PA',
  },
  {
    name: 'Barlow Blevins',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MD',
  },
  {
    name: 'Gertrude Haynes',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'AR',
  },
  {
    name: 'Richard Collier',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'AK',
  },
  {
    name: 'Cora Little',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ME',
  },
  {
    name: 'Avery Yates',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'IN',
  },
  {
    name: 'John Mays',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'HI',
  },
  {
    name: 'Sykes Nguyen',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'ND',
  },
  {
    name: 'Caldwell Nunez',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MN',
  },
  {
    name: 'Dorothea Owens',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'DE',
  },
  {
    name: 'Sims Chen',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'KS',
  },
  {
    name: 'Case Morrison',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'KY',
  },
  {
    name: 'Cook Bryan',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NH',
  },
  {
    name: 'Phillips Rich',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'OK',
  },
  {
    name: 'Bright Frye',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'IA',
  },
  {
    name: 'Kelly Holmes',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'FL',
  },
  {
    name: 'Kasey Farley',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MI',
  },
  {
    name: 'Michele Battle',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'IL',
  },
  {
    name: 'Fanny Nash',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'ID',
  },
  {
    name: 'Nina Reed',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MA',
  },
  {
    name: 'Guerrero Merrill',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NJ',
  },
  {
    name: 'Meadows Barber',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'OH',
  },
  {
    name: 'Adriana Mayer',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'LA',
  },
  {
    name: 'Allyson Mason',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MT',
  },
  {
    name: 'Holland Pugh',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'AL',
  },
  {
    name: 'Janet Stein',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'OR',
  },
  {
    name: 'Beck Greene',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'SC',
  },
  {
    name: 'Baird Hammond',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'NV',
  },
  {
    name: 'Bates Cote',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'GA',
  },
  {
    name: 'Lorraine Shields',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'VA',
  },
  {
    name: 'Luz Mccall',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'WA',
  },
  {
    name: 'Guthrie Moody',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'WY',
  },
  {
    name: 'Mercer Nolan',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'CA',
  },
  {
    name: 'Louella Rogers',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'CT',
  },
  {
    name: 'Berta Carter',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'AZ',
  },
  {
    name: 'Bradley Santos',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'VT',
  },
  {
    name: 'Hendricks Waller',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'TN',
  },
  {
    name: 'Helen Faulkner',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'UT',
  },
  {
    name: 'Combs Steele',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'CO',
  },
  {
    name: 'Hopkins Ashley',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'AK',
  },
  {
    name: 'Ruiz Romero',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'AR',
  },
  {
    name: 'Wheeler Briggs',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'CA',
  },
  {
    name: 'Sampson Lambert',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'WI',
  },
  {
    name: 'Strickland Grant',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NM',
  },
  {
    name: 'Ella Holt',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NE',
  },
  {
    name: 'Garrett Cantu',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'SD',
  },
  {
    name: 'June Holcomb',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'TN',
  },
  {
    name: 'Monica Moody',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NY',
  },
  {
    name: 'Virgie Shields',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NY',
  },
  {
    name: 'Lacey Coleman',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'NC',
  },
  {
    name: 'Jane Kidd',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NC',
  },
  {
    name: 'Patterson Little',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'MS',
  },
  {
    name: 'Bailey Pickett',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MS',
  },
  {
    name: 'Debbie Atkinson',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'TX',
  },
  {
    name: 'Atkinson Slater',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'TX',
  },
  {
    name: 'Kirby Graham',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'KY',
  },
  {
    name: 'Andrea Jensen',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'IN',
  },
  {
    name: 'Young Delacruz',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'FL',
  },
  {
    name: 'Brandy Heath',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'KS',
  },
  {
    name: 'Thomas Wong',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MS',
  },
  {
    name: 'Cox Warren',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'LA',
  },
  {
    name: 'Lindsay Arnold',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'CO',
  },
  {
    name: 'Hoover Brown',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'ID',
  },
  {
    name: 'Little Grant',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'WY',
  },
  {
    name: 'Rollins Byrd',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'IA',
  },
  {
    name: 'Olive Hill',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'DE',
  },
  {
    name: 'Hamilton Carver',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'ME',
  },
  {
    name: 'Burt Garner',
    hebName: 'אבגד הוזח',
    position: 'tossup',
    state: 'MI',
  },
  {
    name: 'Kim Mckay',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'MN',
  },
  {
    name: 'Peterson Bolton',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'NE',
  },
  {
    name: 'Abby Adams',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'NJ',
  },
  {
    name: 'Megan Fleming',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'NH',
  },
  {
    name: 'Burton Stewart',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'SD',
  },
  {
    name: 'Erica Contreras',
    hebName: 'אבגד הוזח',
    position: 'dem-leaning',
    state: 'UT',
  },
  {
    name: 'Gonzalez Boyd',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'RI',
  },
  {
    name: 'Weeks Humphrey',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MA',
  },
  {
    name: 'Essie Sawyer',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'MD',
  },
  {
    name: 'Ina Madden',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'CT',
  },
  {
    name: 'Mitchell Mays',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'HI',
  },
  {
    name: 'Rush Spencer',
    hebName: 'אבגד הוזח',
    position: 'dem',
    state: 'GA',
  },
  {
    name: 'Mckinney Burke',
    hebName: 'אבגד הוזח',
    position: 'gop',
    state: 'IL',
  },
  {
    name: 'Mack Hardy',
    hebName: 'אבגד הוזח',
    position: 'gop-leaning',
    state: 'TX'
  }
]
